name: CI Workflow

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  health_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Health check
        run: |
            npm ci
            npm run lint


  publish:
    runs-on: ubuntu-latest
    needs: health_check
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Authenticate to npm
        run: |
            echo "Setting environments"
            npm ci
            npm run publish:package
        env:
          NPM_TOKEN: ${{ secrets.NPM_SECRET }}
